[global]
keyboard = "en-us"
country = "us"
fqdn = "pbs01.local"
mailto = "root@pbs01.local"
timezone = "America/New_York"
root_password = "admin123$"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk_list = ["/dev/sda"]