[global]
keyboard = "en-us"
country = "us"
fqdn = "vm-pbs-ds918p-01.local"
mailto = "root@vm-pbs-ds918p-01.local"
timezone = "America/Indiana/Indianapolis"
root_password = "admin123$"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk_list = ["/dev/sda"]
